import type { FixTemplate } from "../types";

export const contentTemplates: Record<string, FixTemplate> = {
  "links.broken-internal": { goal: "Restore a working internal navigation path.", guidance: ["Locate the source link and confirm the intended destination with the existing routes and product flow.", "Update the link or restore the destination; do not invent a replacement route."], acceptanceCriteria: ["Every listed source-to-target path returns a successful intended page or uses the confirmed replacement URL.", "No working navigation path is removed.", "A deployed link check and project tests pass."] },
  "links.placeholder": { goal: "Replace development placeholder links with intentional behavior.", guidance: ["Identify the intended action for each observed placeholder with the owner when it is not evident from existing routes.", "Use a real destination or an appropriate non-link control; do not invent product destinations."], acceptanceCriteria: ["Listed placeholder anchors no longer use empty, hash-only, or javascript:void targets.", "Each replacement performs an intentional accessible action.", "Existing navigation tests pass."] },
  "content.placeholder": { goal: "Remove verified development placeholder content before launch.", guidance: ["Locate the observed placeholder text and confirm the intended final content with the owner.", "Replace only with accurate approved content; do not fabricate business claims."], acceptanceCriteria: ["The exact observed placeholder content is absent from affected public pages.", "Replacement content is owner-approved and accurate.", "The visual layout and build remain valid."] },
  "accessibility.image-alt-missing": { goal: "Provide appropriate text alternatives for the affected images.", guidance: ["Inspect each image's purpose in context.", "Add meaningful alt text for informative images; use an empty alt attribute for decorative images rather than inventing descriptions."], acceptanceCriteria: ["Each listed image has an appropriate alt attribute.", "Decorative images do not create redundant announcements.", "Existing accessibility checks pass."] },
  "accessibility.form-label-missing": { goal: "Give each affected form control an accessible name.", guidance: ["Inspect the rendered form and existing component conventions.", "Associate a visible label where appropriate, or use an accurate aria-label/aria-labelledby when a visible label is not suitable."], acceptanceCriteria: ["Every listed control has an accessible name.", "Labels describe the real input purpose.", "Keyboard and existing form behavior remain intact."] },
  "accessibility.headings-missing": { goal: "Add a meaningful heading structure to the affected page.", guidance: ["Inspect the actual content hierarchy before editing.", "Introduce headings that describe existing sections without using heading levels for visual styling alone."], acceptanceCriteria: ["The page contains headings that reflect its content structure.", "Heading text matches actual content.", "Visual design remains consistent."] },
  "accessibility.heading-level-jump": { goal: "Make the affected heading sequence reflect a coherent hierarchy.", guidance: ["Inspect surrounding sections and determine the intended nesting.", "Adjust semantic heading levels while preserving the existing visual treatment where possible."], acceptanceCriteria: ["The verified heading-level jump is resolved.", "The document outline remains meaningful.", "No visual regression is introduced."] },
  "structured-data.jsonld-invalid": { goal: "Make the existing JSON-LD block syntactically valid JSON.", guidance: ["Locate the exact JSON-LD generation path in the current framework.", "Correct JSON syntax only; verify actual structured-data values with the owner and do not invent Schema.org claims."], acceptanceCriteria: ["Every affected JSON-LD block parses as JSON.", "Structured values reflect real page content.", "The deployed page and existing tests pass."] },
};
