"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

const checks = ["Indexability", "Metadata", "Broken links", "Accessibility basics", "Security headers"];

export default function HomePage() {
  const router = useRouter(); const [url, setUrl] = useState(""); const [message, setMessage] = useState<string | null>(null);
  function startScan(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!url.trim()) { setMessage("Enter a public website URL to continue."); return; } setMessage(null); void fetch("/api/scans", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ url: url.trim() }) }).then(async (response) => { const payload = await response.json() as { id?: string; error?: string }; if (!response.ok || !payload.id) { setMessage(payload.error ?? "Unable to start scan."); return; } router.push(`/scan/${payload.id}`); }).catch(() => setMessage("Unable to start scan.")); }
  return <main className="min-h-screen overflow-hidden bg-[#07111f]"><div className="mx-auto max-w-6xl px-6 py-6 sm:px-10"><header className="flex items-center justify-between" aria-label="Site header"><span className="text-sm font-semibold tracking-[0.18em] text-cyan-300">AI WEBSITE PREFLIGHT</span><span className="rounded-full border border-slate-700 px-3 py-1 text-xs text-slate-300">Phase 04</span></header>
    <section className="grid min-h-[78vh] items-center gap-12 py-20 lg:grid-cols-[1.15fr_.85fr]"><div><p className="mb-5 text-sm font-medium text-cyan-300">For AI-built websites</p><h1 className="max-w-3xl text-5xl font-semibold tracking-tight text-white sm:text-6xl">Is your AI-built website actually ready to launch?</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Run a preflight check before you publish. Review a transparent Ready Score and reproducible findings for discovery, trust, accessibility basics, and launch mistakes.</p>
      <form className="mt-9 max-w-2xl" onSubmit={startScan} noValidate><label className="sr-only" htmlFor="website-url">Public website URL</label><div className="flex flex-col gap-3 rounded-2xl border border-slate-700 bg-slate-900/70 p-3 shadow-2xl shadow-cyan-950/30 sm:flex-row"><input id="website-url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com" className="min-w-0 flex-1 rounded-xl border border-slate-700 bg-[#0b1627] px-4 py-3 text-white outline-none placeholder:text-slate-500 focus:border-cyan-400" inputMode="url" /><button type="submit" className="rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-slate-950 transition hover:bg-cyan-200 focus:outline-none focus:ring-2 focus:ring-cyan-200">Run Preflight</button></div><p className="mt-3 text-sm text-slate-400">Only public pages will be scanned. We never modify your website.</p>{message ? <p className="mt-3 text-sm text-amber-300" role="alert">{message}</p> : null}</form>
      <ul className="mt-10 flex flex-wrap gap-2" aria-label="Check categories">{checks.map((check) => <li key={check} className="rounded-full border border-slate-700 px-3 py-1.5 text-sm text-slate-300">{check}</li>)}</ul></div>
      <section className="rounded-3xl border border-slate-700 bg-gradient-to-b from-slate-900 to-[#0a1423] p-6 shadow-2xl shadow-slate-950/40" aria-label="Example report"><p className="text-xs uppercase tracking-[0.2em] text-slate-400">Example report</p><div className="mt-5 rounded-xl border border-amber-400/30 bg-amber-400/5 p-4"><p className="text-4xl font-semibold text-amber-100">84 <span className="text-base text-amber-300">/ 100</span></p><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-amber-300">Almost ready</p><p className="mt-3 text-sm leading-6 text-slate-300">Every deduction is tied to a deterministic rule and reproducible evidence.</p></div><p className="mt-5 text-sm leading-6 text-slate-400">Ready Score summarizes automated checks on sampled pages. It is not a complete security, compliance, or quality assessment.</p></section></section></div></main>;
}
